name: R2 Directory Synchronizer

on:
  push:
    branches:
      - main # or specify the branches you want to trigger this action on

jobs:
  r2Backup:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: R2 Backup
      uses: JoseMoranUrena523/r2-backup@v1.0.0
      env:
        ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
        BUCKET_NAME: ariscorp-p4k-files
        SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
      with:
        args: --overwrite --remove
