name: R2 Directory Synchronizer

on:
  push:
    branches:
      - main # or specify the branches you want to trigger this action on

jobs:
  r2Backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean unused objects
        run: |
          ls
