name: Upload to R2
on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  Fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean unused objects
        run: |
          ls -a
          rm -rf ./.git
          rm -rf ./.github
          rm -rf ./.tools
          rm -rf ./.gitignore
          rm -rf ./README.md
          rm -rf ./cover.png
          rm -rf ./run.bat
          rm -rf ./latest/json/factions
          rm -rf ./latest/json/items
          rm -rf ./latest/json/loot
          rm -rf ./latest/json/missions
          rm -rf ./latest/json/reputation
          rm -rf ./latest/json/ships
          rm -rf ./latest/json/fps-items.json
          rm -rf ./latest/json/items.json
          rm -rf ./latest/json/labels.json
          rm -rf ./latest/json/manufacturers.json
          rm -rf ./latest/json/ship-items.json
          rm -rf ./latest/json/ships.json
          rm -rf ./latest/json/starmap.json
          rm -rf ./latest/json/v2/items
          ls -a

      - name: Archive objects
        run: |
          zip -0 -r latest-p4k-files.zip ./latest/json/*
        # zip -0 -r old-p4k-files.zip ./* -x "latest/"

      - name: Upload latest-p4k-files
        uses: actions/upload-artifact@v4.3.1
        with:
          name: latest-p4k-files
          path: latest-p4k-files.zip
          retention-days: 1
          compression-level: 0

      #- name: Upload old-p4k-files
      #  uses: actions/upload-artifact@v4.3.1
      #  with:
      #    name: old-p4k-files
      #    path: old-p4k-files.zip
      #    retention-days: 1
      #    compression-level: 0

  Sync-Latest-P4K-Files:
    runs-on: ubuntu-latest
    needs: Fetch
    steps:
      - name: Download Archive Artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: latest-p4k-files

      - name: Extract Archive
        run: unzip -qq latest-p4k-files.zip -d latest-p4k-files

      - name: Sync Latest P4K Files
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ariscorp-p4k-files
          source-dir: latest-p4k-files
          destination-dir: ./
          output-file-url: false
          keep-file-fresh: true

  #Sync-Old-P4K-Files:
  #  runs-on: ubuntu-latest
  #  needs: Fetch
  #  steps:
  #    - name: Download Archive Artifact
  #      uses: actions/download-artifact@v4.1.4
  #      with:
  #        name: old-p4k-files

  #    - name: Extract Archive
  #      run: unzip -qq old-p4k-files.zip -d old-p4k-files

  #    - name: Sync Old P4K Files
  #      uses: ryand56/r2-upload-action@latest
  #      with:
  #        r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
  #        r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
  #        r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
  #        r2-bucket: ariscorp-p4k-files
  #        source-dir: old-p4k-files
  #        destination-dir: ./
  #        output-file-url: false

  Purge-Cache:
    runs-on: ubuntu-latest
    if: always() # always purge cache whenever it fails or succeed
    needs: [
      Sync-Latest-P4K-Files,
      #Sync-Old-P4K-Files
    ]
    steps:
      - name: Purge Cloudflare cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/89a78ad51ccd1b2a47cffe23b225575f/purge_cache" \
              -H "Authorization: Bearer ${{ secrets.CF_PURGE_CACHE_TOKEN }}" \
              -H "Content-Type: application/json" \
              --data "{ \"purge_everything\": true }"
